import { el } from '../core/element.js';

const signs = Object.freeze({ add: '+', delete: '−', context: '', note: '' });
const prefixes = Object.freeze({ add: 'addition', delete: 'deletion', context: 'context' });

/**
 * The rows of one file's hunks: first planned as data (cheap, so a large file can be drawn in chunks),
 * then each drawn as a node.
 *
 * - A hunk's header row says its ranges and section ("@@ -12,7 +12,9 @@ function name"); `]` and `[`
 *   reach it (`tabindex="-1"`).
 * - Between hunks whose old lines skip, a muted row says how many lines are not in this patch: never an
 *   expander, since the input does not carry them.
 * - Inside a hunk, a run of more than `2 × context + 2` unchanged lines keeps `context` lines at each end
 *   and folds its middle behind "Show {n} unchanged lines", which reveals exactly the input's lines.
 * - A line's numbers and sign are generated by the stylesheet from `data-number` and `data-sign` in an
 *   `aria-hidden` gutter, so a selection of the code copies only code; a hidden prefix that a selection
 *   skips says "Added line 12:", "Removed line 9:" or "Line 14:" when a screen reader reaches the line.
 */
export class DiffRows {
	#words;
	#context;

	/**
	 * @param {import('./words.js').DiffWords} words
	 * @param {number} context the unchanged lines kept at each end of a folded run
	 */
	constructor(words, context) {
		this.#words = words;
		this.#context = Math.max(0, Math.floor(context));
	}

	/** The rows of a file's hunks, in order, as descriptors. */
	plan(entry) {
		const rows = [];
		let previous = null;
		for (const hunk of entry.hunks) {
			if (previous) {
				const end = previous.before ? previous.old + previous.before : previous.old + 1;
				const skipped = (hunk.before ? hunk.old : hunk.old + 1) - end;
				if (skipped > 0) rows.push({ type: 'gap', count: skipped });
			}
			rows.push({ type: 'hunk', text: DiffRows.title(hunk) });
			rows.push(...this.#fold(DiffRows.#lines(hunk)));
			previous = hunk;
		}
		return rows;
	}

	/** A hunk's header as git writes it, with its section. */
	static title(hunk) {
		const range = (start, count) => (count === 1 ? `${start}` : `${start},${count}`);
		return `@@ -${range(hunk.old, hunk.before)} +${range(hunk.new, hunk.after)} @@${hunk.header ? ` ${hunk.header}` : ''}`;
	}

	/** The widest line number of a plan, for the gutter's width. */
	static digits(rows) {
		let widest = 1;
		for (const row of rows) for (const line of row.type === 'more' ? row.rows : [row]) widest = Math.max(widest, String(line.old ?? '').length, String(line.new ?? '').length);
		return widest;
	}

	/**
	 * One row's node. `reveal(row, node)` is called when a folded run's button is pressed.
	 * @returns {HTMLElement}
	 */
	node(row, reveal) {
		if (row.type === 'hunk') return el('div', { class: 'bui-diff-hunk', tabindex: '-1' }, [el('span', { class: 'bui-diff-aside' }, [row.text])]);
		if (row.type === 'gap') return el('div', { class: 'bui-diff-gap' }, [el('span', { class: 'bui-diff-aside' }, [this.#words.count('gap', row.count)])]);
		if (row.type === 'more') {
			const node = el('div', { class: 'bui-diff-more' });
			const button = el('button', { type: 'button', class: 'bui-diff-reveal', onclick: () => reveal(row, node) }, [this.#words.count('more', row.rows.length)]);
			node.append(el('span', { class: 'bui-diff-aside' }, [button]));
			return node;
		}
		return this.#line(row);
	}

	#line(row) {
		const number = row.kind === 'add' ? row.new : row.kind === 'delete' ? row.old : row.new;
		const said = row.kind === 'note' ? null : el('span', { class: 'bui-hidden bui-diff-said' }, [this.#words.text(prefixes[row.kind], { number: this.#words.number(number) })]);
		const text = row.kind === 'note' ? this.#words.text('newline') : row.text;
		return el('div', { class: 'bui-diff-line', dataset: { kind: row.kind } }, [
			el('span', { class: 'bui-diff-gutter', 'aria-hidden': 'true' }, [
				el('span', { class: 'bui-diff-num', 'data-number': row.old ?? '' }),
				el('span', { class: 'bui-diff-num', 'data-number': row.new ?? '' }),
				el('span', { class: 'bui-diff-sign', 'data-sign': signs[row.kind] })
			]),
			el('span', { class: 'bui-diff-code' }, [said, text])
		]);
	}

	/** A hunk's lines with their old and new numbers. */
	static #lines(hunk) {
		let old = hunk.before ? hunk.old : hunk.old + 1;
		let next = hunk.after ? hunk.new : hunk.new + 1;
		return hunk.lines.map(line => {
			if (line.kind === 'note') return { type: 'line', kind: 'note', text: line.text, old: null, new: null };
			const row = { type: 'line', kind: line.kind, text: line.text, old: line.kind === 'add' ? null : old, new: line.kind === 'delete' ? null : next };
			if (line.kind !== 'add') old += 1;
			if (line.kind !== 'delete') next += 1;
			return row;
		});
	}

	/** Folds the middle of every run of unchanged lines longer than `2 × context + 2`. */
	#fold(lines) {
		const rows = [];
		const keep = this.#context;
		let run = [];
		const flush = () => {
			if (run.length > 2 * keep + 2) rows.push(...run.slice(0, keep), { type: 'more', rows: run.slice(keep, run.length - keep) }, ...run.slice(run.length - keep));
			else rows.push(...run);
			run = [];
		};
		for (const line of lines) {
			if (line.kind === 'context') run.push(line);
			else {
				flush();
				rows.push(line);
			}
		}
		flush();
		return rows;
	}
}
