import { test, after, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { Page } from './support/page.mjs';

/** Diff's drawing (0.11.2): files as regions named by their paths, headers in words, lines read with their prefix, gaps and folded runs from the input only, notes, the summary and the list of files, Copy path, Spanish. */
const page = new Page();
const ui = await import('@beyond-js/ui/dom');
const { Diff } = ui;
after(() => page.close());
beforeEach(() => page.reset());
const fixture = name => readFileSync(new URL(`./fixtures/diff/${name}.patch`, import.meta.url), 'utf8');
const mount = options => new Diff(options).mount(document.body);
const file = (diff, path) => [...diff.element.querySelectorAll('.bui-diff-file')].find(node => node.dataset.path === path);

test('each file is a region named by its path, with a heading holding the disclosure button: path, status in words and counts with their sentence', () => {
	const diff = mount({ patch: fixture('git') });
	const root = diff.element;
	assert.equal(root.tagName, 'SECTION');
	assert.equal(root.getAttribute('aria-label'), 'Changes');
	assert.equal(document.getElementById(root.getAttribute('aria-describedby')).textContent, 'Arrow keys move between files; ] and [ move between hunks.');
	const sections = [...root.querySelectorAll('section.bui-diff-file')];
	assert.deepEqual(sections.map(node => document.getElementById(node.getAttribute('aria-labelledby')).textContent), ['src/app.js', 'docs/notes.md', 'old/legacy.txt']);
	assert.deepEqual(sections.map(node => node.dataset.status), ['modified', 'added', 'deleted']);
	const app = sections[0];
	const toggle = app.querySelector('h3.bui-diff-heading > button.bui-diff-toggle');
	assert.equal(toggle.getAttribute('aria-expanded'), 'true');
	assert.ok(document.getElementById(toggle.getAttribute('aria-controls')) === app.querySelector('.bui-diff-body'));
	assert.ok(toggle.querySelector('.bui-diff-chevron svg[data-icon="chevron"]'), 'the chevron beside the words');
	assert.equal(app.querySelector('.bui-diff-dir').textContent, 'src/');
	assert.equal(app.querySelector('.bui-diff-name').textContent, 'app.js');
	assert.deepEqual(sections.map(node => node.querySelector('.bui-diff-status').textContent), ['Modified', 'Added', 'Deleted']);
	const count = app.querySelector('.bui-diff-count');
	assert.equal(count.querySelector('[aria-hidden="true"]').textContent, '+2 −1');
	assert.equal(count.querySelector('.bui-hidden').textContent, '2 added lines, 1 removed line');
	assert.equal(sections[2].querySelector('.bui-diff-count .bui-hidden').textContent, '0 added lines, 3 removed lines');
	assert.ok(app.hasAttribute('data-open'));
	diff.destroy();
});

test('lines: numbers and signs generated in a hidden gutter, a prefix said by a screen reader, the code as written; hunk headers, a gap between hunks and the note', () => {
	const diff = mount({ patch: fixture('git') });
	const app = file(diff, 'src/app.js');
	const box = app.querySelector('.bui-diff-lines');
	assert.equal(box.getAttribute('tabindex'), '0');
	assert.equal(box.getAttribute('aria-label'), 'Lines of src/app.js');
	const rows = [...box.querySelector('.bui-diff-rows').children];
	assert.deepEqual(rows.map(row => row.className.replace('bui-diff-', '') + (row.dataset.kind ? `:${row.dataset.kind}` : '')), ['hunk', 'line:context', 'line:add', 'line:context', 'line:context', 'line:context', 'gap', 'hunk', 'line:context', 'line:delete', 'line:add', 'line:context', 'line:note']);
	assert.equal(rows[0].textContent, '@@ -1,4 +1,5 @@');
	assert.equal(rows[0].getAttribute('tabindex'), '-1');
	assert.equal(rows[7].textContent, '@@ -20,3 +21,3 @@ function close(server) {', 'the section as given');
	assert.equal(rows[6].textContent, '15 unchanged lines not in this patch', 'never an expander');
	assert.equal(rows[6].querySelector('button'), null);
	const added = rows[2];
	const gutter = added.querySelector('.bui-diff-gutter');
	assert.equal(gutter.getAttribute('aria-hidden'), 'true');
	assert.deepEqual([...gutter.querySelectorAll('.bui-diff-num')].map(node => node.dataset.number), ['', '2']);
	assert.equal(gutter.querySelector('.bui-diff-sign').dataset.sign, '+');
	assert.equal(gutter.textContent, '', 'numbers and signs are generated, so a selection never copies them');
	assert.equal(added.querySelector('.bui-diff-said').textContent, 'Added line 2: ');
	assert.equal(added.querySelector('.bui-diff-code').textContent, "Added line 2: import { stop } from './stop.js';");
	assert.equal(rows[9].querySelector('.bui-diff-said').textContent, 'Removed line 21: ');
	assert.equal(rows[9].querySelector('.bui-diff-sign').dataset.sign, '−');
	assert.deepEqual([...rows[9].querySelectorAll('.bui-diff-num')].map(node => node.dataset.number), ['21', '']);
	assert.equal(rows[8].querySelector('.bui-diff-said').textContent, 'Line 21: ');
	assert.equal(rows[12].textContent, 'No newline at end of file');
	assert.equal(rows[12].querySelector('.bui-diff-said'), null);
	assert.equal(box.style.getPropertyValue('--bui-diff-digits'), '2');
	diff.destroy();
});

test('a long run of unchanged lines folds its middle; Show reveals exactly the input’s lines in place', () => {
	const diff = mount({ patch: fixture('context') });
	const box = diff.element.querySelector('.bui-diff-lines');
	const kinds = () => [...box.querySelector('.bui-diff-rows').children].map(row => row.dataset.kind ?? row.className.replace('bui-diff-', ''));
	assert.deepEqual(kinds(), ['hunk', 'delete', 'add', 'context', 'context', 'context', 'more', 'context', 'context', 'context', 'delete', 'add']);
	const button = box.querySelector('.bui-diff-more button');
	assert.equal(button.textContent, 'Show 8 unchanged lines');
	assert.deepEqual([...box.querySelectorAll('.bui-diff-line[data-kind="context"] .bui-diff-said')].map(node => node.textContent), ['Line 2: ', 'Line 3: ', 'Line 4: ', 'Line 13: ', 'Line 14: ', 'Line 15: ']);
	button.focus();
	button.click();
	assert.equal(box.querySelector('.bui-diff-more'), null);
	const shown = [...box.querySelectorAll('.bui-diff-line[data-kind="context"]')].map(row => row.querySelector('.bui-diff-code').lastChild.textContent);
	assert.deepEqual(shown, Array.from({ length: 14 }, (_, at) => `line ${at + 2}`), 'exactly the lines of the input, in order');
	assert.ok(document.activeElement === box, 'focus stays in the file');
	const short = mount({ files: [{ path: 'a.txt', hunks: [{ old: 1, new: 1, lines: ['-a', '+b', ...Array.from({ length: 8 }, (_, at) => ` ${at}`), '-c', '+d'] }] }] });
	assert.equal(short.element.querySelector('.bui-diff-more'), null, 'a run of 2 × context + 2 lines stays whole');
	diff.destroy();
	short.destroy();
});

test('notes: binary, renamed and copied without changes, mode only, an empty file, whitespace only, unread', () => {
	const notes = diff => [...diff.element.querySelectorAll('.bui-diff-file')].map(node => [node.querySelector('.bui-diff-status').textContent, [...node.querySelectorAll('.bui-diff-note')].map(note => note.textContent).join(' | '), node.querySelectorAll('.bui-diff-line').length]);
	const moves = mount({ patch: fixture('moves'), open: 'all' });
	assert.deepEqual(notes(moves).slice(1), [['Renamed', 'Renamed without changes', 0], ['Copied', 'Copied without changes', 0], ['Mode changed', 'File mode changed from 100644 to 100755', 0]]);
	const rename = moves.element.querySelector('.bui-diff-file .bui-diff-path');
	assert.equal(rename.textContent, 'src/old-name.js →  to src/new-name.js');
	assert.equal(rename.querySelector('.bui-diff-arrow').getAttribute('aria-hidden'), 'true');
	const binary = mount({ patch: fixture('binary'), open: 'all' });
	assert.deepEqual(notes(binary), [['Modified', 'Binary file · not shown', 0], ['Added', 'Binary file · not shown', 0], ['Added', 'Empty file', 0]]);
	const counts = [...binary.element.querySelectorAll('.bui-diff-head .bui-diff-count')].map(node => node.textContent);
	assert.deepEqual(counts.slice(0, 2), ['Binary', 'Binary'], 'a binary file is said as such, never "+0 −0"');
	const space = mount({ patch: fixture('whitespace') });
	assert.deepEqual(notes(space), [['Modified', 'Whitespace changes only', 4]], 'the lines still show');
	const broken = mount({ patch: fixture('malformed'), open: 'all' });
	assert.deepEqual(notes(broken).map(([, note]) => note), ['This part of the patch couldn’t be read', '']);
	assert.equal(broken.element.querySelectorAll('.bui-diff-line').length, 5 + 2, 'the rest is shown');
	const nothing = mount({ patch: 'just words' });
	assert.equal(nothing.element.querySelector('.bui-diff-top').textContent, 'This part of the patch couldn’t be read');
	const empty = mount({ patch: '' });
	assert.equal(empty.element.querySelector('.bui-diff-top').textContent, 'No changes');
	for (const diff of [moves, binary, space, broken, nothing, empty]) diff.destroy();
});

test('the summary with Open all and Fold all from two files; the list of files from Diff.jump files, each opening, scrolling to and focusing its file', () => {
	const one = mount({ files: [{ path: 'a.txt', hunks: [{ old: 1, new: 1, lines: ['+a'] }] }] });
	assert.equal(one.element.querySelector('.bui-diff-total').textContent, '1 file changed · +1 −0' + '1 added line, 0 removed lines');
	assert.equal(one.element.querySelector('.bui-diff-actions'), null, 'one file has nothing to open all');
	assert.equal(one.element.querySelector('.bui-diff-jump'), null);
	const three = mount({ patch: fixture('git') });
	assert.match(three.element.querySelector('.bui-diff-total').textContent, /^3 files changed · \+4 −4/);
	assert.equal(three.element.querySelector('.bui-diff-jump'), null, 'three files need no list');
	const [open, fold] = three.element.querySelectorAll('.bui-diff-actions button');
	assert.deepEqual([open.textContent, fold.textContent], ['Open all', 'Fold all']);
	fold.click();
	assert.equal(three.element.querySelectorAll('.bui-diff-file[data-open]').length, 0);
	open.click();
	assert.equal(three.element.querySelectorAll('.bui-diff-file[data-open]').length, 3);
	const bare = mount({ patch: fixture('git'), summary: false, label: 'Changes of the conversation', level: 4 });
	assert.equal(bare.element.querySelector('.bui-diff-summary'), null);
	assert.equal(bare.element.getAttribute('aria-label'), 'Changes of the conversation');
	assert.equal(bare.element.querySelectorAll('h4.bui-diff-heading').length, 3);
	const four = mount({ patch: fixture('git') + fixture('whitespace'), open: 'none' });
	const nav = four.element.querySelector('nav.bui-diff-jump');
	assert.equal(nav.getAttribute('aria-label'), 'Files in this change');
	const items = [...nav.querySelectorAll('li > button.bui-diff-jump-item')];
	assert.deepEqual(items.map(item => [item.querySelector('.bui-diff-path').textContent, item.querySelector('.bui-diff-status').textContent, item.querySelector('.bui-diff-count .bui-hidden').textContent]).at(-1), ['src/format.js', 'Modified', '1 added line, 1 removed line']);
	const target = file(four, 'src/format.js');
	let scrolled = null;
	target.scrollIntoView = options => (scrolled = options);
	items.at(-1).click();
	assert.ok(target.hasAttribute('data-open'), 'opened');
	assert.deepEqual(scrolled, { behavior: 'smooth', block: 'start' });
	assert.ok(document.activeElement === target.querySelector('.bui-diff-toggle'), 'focus on its header');
	for (const diff of [one, three, bare, four]) diff.destroy();
});

test('open, close and reveal by path; reveal scrolls at once under reduced motion; an unknown path is false', () => {
	const diff = mount({ patch: fixture('git'), open: 'none' });
	assert.equal(diff.element.querySelectorAll('.bui-diff-line').length, 0, 'folded files hold no lines');
	assert.equal(diff.open('docs/notes.md'), true);
	assert.ok(file(diff, 'docs/notes.md').hasAttribute('data-open'));
	assert.equal(file(diff, 'docs/notes.md').querySelector('.bui-diff-toggle').getAttribute('aria-expanded'), 'true');
	assert.equal(diff.close('docs/notes.md'), true);
	assert.equal(file(diff, 'docs/notes.md').querySelector('.bui-diff-body').hidden, true);
	assert.equal(diff.open('nope'), false);
	assert.equal(diff.reveal('nope'), false);
	const original = window.matchMedia;
	window.matchMedia = query => ({ matches: /reduce/.test(query), media: query, addEventListener() {}, removeEventListener() {} });
	let scrolled = null;
	file(diff, 'old/legacy.txt').scrollIntoView = options => (scrolled = options);
	assert.equal(diff.reveal('old/legacy.txt'), true);
	window.matchMedia = original;
	assert.deepEqual(scrolled, { behavior: 'auto', block: 'start' });
	assert.ok(document.activeElement === file(diff, 'old/legacy.txt').querySelector('.bui-diff-toggle'));
	diff.destroy();
});

test('Copy path copies the new path (the old one for a deletion) through the clipboard and says Copied in place; Spanish', async () => {
	const copied = [];
	const clipboard = { writeText: async text => void copied.push(text) };
	Object.defineProperty(window.navigator, 'clipboard', { value: clipboard, configurable: true });
	const diff = mount({ patch: fixture('git') + fixture('moves') });
	const button = file(diff, 'old/legacy.txt').querySelector('.bui-copy-button button');
	assert.equal(button.textContent, 'Copy path');
	assert.equal(button.getAttribute('aria-label'), 'Copy the path old/legacy.txt');
	button.click();
	await page.until(() => copied.length === 1);
	await page.until(() => button.textContent === 'Copied');
	assert.deepEqual(copied, ['old/legacy.txt']);
	file(diff, 'src/new-name.js').querySelector('.bui-copy-button button').click();
	await page.until(() => copied.length === 2);
	assert.equal(copied[1], 'src/new-name.js');
	const spanish = mount({ patch: fixture('git'), labels: Diff.labels.es, locale: 'es' });
	const root = spanish.element;
	assert.equal(root.getAttribute('aria-label'), 'Cambios');
	assert.match(root.querySelector('.bui-diff-total').textContent, /^3 archivos cambiados/);
	assert.deepEqual([...root.querySelectorAll('.bui-diff-file .bui-diff-status')].map(node => node.textContent), ['Modificado', 'Añadido', 'Eliminado']);
	assert.equal(root.querySelector('.bui-diff-line[data-kind="add"] .bui-diff-said').textContent, 'Línea añadida 2: ');
	assert.equal(root.querySelector('.bui-diff-gap').textContent, '15 líneas sin cambios fuera de este parche');
	assert.equal(root.querySelector('.bui-diff-line[data-kind="note"]').textContent, 'Sin salto de línea al final del archivo');
	const copy = root.querySelector('.bui-copy-button button');
	assert.deepEqual([copy.textContent, copy.getAttribute('aria-label')], ['Copiar ruta', 'Copiar la ruta src/app.js']);
	copy.click();
	await page.until(() => copy.textContent === 'Copiado');
	const thousands = mount({ files: [{ path: 'big.txt', added: 1234, removed: 0 }], labels: Diff.labels.es, locale: 'es' });
	assert.match(thousands.element.querySelector('.bui-diff-count .bui-hidden').textContent, /^1234 líneas añadidas|^1\.234 líneas añadidas/);
	diff.destroy();
	spanish.destroy();
	thousands.destroy();
	delete window.navigator.clipboard;
});
